return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			"bash-language-server",
			"css-variables-language-server",
			"docker-compose-language-service",
			"dockerfile-language-server",
			"eslint-lsp",
			"eslint_d",
			"hadolint",
			"json-lsp",
			"lua-language-server",
			"markdown-toc",
			"markdownlint-cli2",
			"marksman",
			"prettier",
			"prettierd",
			"rescript-language-server",
			"shellcheck",
			"shfmt",
			"sqlfluff",
			"stylelint-lsp",
			"stylua",
			"taplo",
			"terraform-ls",
			"tflint",
			"tree-sitter-cli",
			"tsgo",
			"yaml-language-server",
		},
	},
}
